### ISSUE TITLE
[Idea] Make glitter shape customizable inside flutter

### ISSUE THREAD

**Issue by TheDonCortez** [kaboc/flutter_glitters#10]
**Situation:**
At this moment it seems like there is only one default shape for the 'glitter'.

**Complication:**
Although this shape already looks like a glitter/star, sometimes I want to use a different show to fade in and out of the screen. This is however currently not possible.

**Challenge:**
It would be great if you can make this shape customizable.

**Solution:**
Maybe using the flutter Icons, so the user can set what 'icon' should be used as glitter.
Similar to the way it has been done in this package: https://pub.dev/packages/animate_icons

**Comment by kaboc** [comment]
Sounds interesting! Thanks for the nice suggestion.
I'll see its if it's possible with a small change, consider other tasks and priority / my time, and then make a decision.

**Comment by kaboc** [comment]
@TheDonCortez 
I tried implementing it, and it came out nicer than I expected. Is this what you want?
A good thing about it is that icons/widgets look good also on a light background, while the pre-defined glitters look ugly there.

| With icons | With widgets (images[^image] in this example) |
|---|---|
| <img src="https://user-images.githubusercontent.com/20254485/149598957-2c0334e0-7ab7-44ab-af28-fb8bda520034.gif" width="360"> | <img src="https://user-images.githubusercontent.com/20254485/149599016-fa0b7bcd-4d46-4c6a-8bdf-e3b76c0d4293.gif" width="360"> |

[^image]: <a href="https://www.flaticon.com/free-icons/shine" title="shine icons">Shine icons created by srip - Flaticon</a>

But if used with wrong icons as below, it looks very strange and you can't call it "glitters" any more, so I'm wondering if this new feature should really be released... What do you think?

![glitters_icon](https://user-images.githubusercontent.com/20254485/149599415-63ce8169-f22d-46a2-93a0-95266cd0133a.gif)

**Comment by TheDonCortez** [comment]
@kaboc that looks really interesting, and gives endless opportunities for the user. You are right that some shapes don't really look like an archetype 'glitter' immediately (if the user would use 'arrow' icons then it looks.. different). However that does give the user a lot of nice flexibility to create randomized particle backgrounds, which is very useful.

Looking around on the internet for 'Glitter' I see that glitters come in many forms and shapes. They can be round, triangular or stars as well. Whats nice about your original glitter is that it has 'rays' coming out of it, which instantly givws it a shiny feel. However when using a different 'clean' shape, its missing the blurry / glowing (nice feature as well btw) edge to make it an 'official' glitter. 

So I would personally implement this feature, maybe see if you can keep your original glitter as default and let users overwrite it with Flutter Icons OR choose a Flutter Icon that you like and set it as default.

Btw, really cool the quick development on your side!

**Comment by kaboc** [comment]
Agreed!

I'll probably add two named constructors:

- Glitters.icon
- Glitters.widget

This feature will be released together with another feature requested in #11, or separately if #11 will not easy.

**Comment by kaboc** [comment]
v0.4.0 was released with this feature!
